name: etcd-node2
data-dir: /Users/jingyao.deng/Desktop/everythin9/etcd/data/node2
initial-cluster-state: new
initial-cluster-token: etcd-cluster-token
initial-cluster: etcd-node1=http://127.0.0.1:2380,etcd-node2=http://127.0.0.1:2381,etcd-node3=http://127.0.0.1:2382
initial-advertise-peer-urls: http://127.0.0.1:2381
listen-peer-urls: http://127.0.0.1:2381
listen-client-urls: http://127.0.0.1:2378
advertise-client-urls: http://127.0.0.1:2378
logger: zap